name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - run: go mod tidy
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_go_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.4.1 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - run: go test ./...
