name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.21", "1.20"]
        pgvector: ["v0.5.1", "master"]
        postgres: [16, 14]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go mod tidy
      - uses: ankane/setup-postgres@v1
        with:
          postgres-version: ${{ matrix.postgres }}
          database: pgvector_go_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch ${{ matrix.pgvector }} https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - run: go test -v
      - run: go generate ./ent && go mod tidy
        working-directory: third-party-tests
      - run: go test -v
        working-directory: third-party-tests
