name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - run: go mod tidy
    - uses: ankane/setup-postgres@v1
      with:
        database: pgvector_go_test
    - run: |
        sudo apt-get update && sudo apt-get install postgresql-server-dev-13
        git clone --branch v0.1.8 https://github.com/ankane/pgvector.git
        cd pgvector
        make
        sudo make install
    - run: go test ./...
