name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # panic with Ent 0.12.4 and Go 1.22
        # fixed in Ent 0.13.0, but requires Go 1.21+
        go: ["1.21", "1.20"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: false # depends on go.sum
      - run: go mod tidy
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_go_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.6.2 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - run: go generate ./ent && go mod tidy
      - run: go test -v
